blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/Zentar-Ai/Zentara-Codediscussions/categories/feature-requests
      about: Share and vote on feature requests for Zentara Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=ZentarAI.zentara-code&ssr=false#review-details
      about: Enjoying Zentara Code? Leave a review here!
