blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/Zentar-Ai/Roo-Codediscussions/categories/feature-requests
      about: Share and vote on feature requests for Roo Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=ZentarAI.roo-code&ssr=false#review-details
      about: Enjoying Roo Code? Leave a review here!
